### ISSUE TITLE
umi-plugin-antd-theme 如果变量引入的是图片资源，在 network disabled cache 的条件下会重复加载

### ISSUE THREAD

**Issue by LittleGragon** [chenshuai2144/umi-plugin-antd-theme#15]
![屏幕录制2020-03-0812 19 09](https://user-images.githubusercontent.com/46911666/76156689-e2d69d00-6138-11ea-8aaf-d01349e761b3.gif)

重现步骤：
1. 声明图片资源变量 并:global 方式使用变量
2. chrome network 设为disabled
3. resize 窗口
4. network 可观察到资源反复加载，导致引用图片资源的样式闪动
```less
// src/global.less
@import '~antd/es/style/themes/default.less';
html,
body,
#root {
  height: 100%;
  --bg: url('@/assets/bg.jpg');
}
```

```less
// src/pages/Welcome.less
@import '~antd/lib/style/themes/default.less';
.pre {
  margin: 12px 0;
  padding: 12px 20px;
  background: @input-bg;
  box-shadow: @card-shadow;
}
:global {
  .ant-layout {
    background: var(--bg);
  }
}
```
