### ISSUE TITLE
插件生成css中的路径问题

### ISSUE THREAD

**Issue by bj75326** [chenshuai2144/umi-plugin-antd-theme#27]
## What happens?

配置theme.config.js 得到的新的css文件中没有对某些路径进行处理

例如
```css
.test {
  background-image: url(../assets/bg2.svg);
}
```
通过umi配置正常打包会生成
```css
.antd-pro-pages-index-test {
    background-image: url(./static/bg2.a54dfde0.svg);
}
```
而通过插件新生成的css中对路径并没有处理
```css
.antd-pro-pages-index-test {
    background-image:url(../assets/bg2.svg);
}
```
## Mini Showcase Repository(REQUIRED)

N.A.

## How To Reproduce

N.A.

## Context

- **Umi Version**: 3.2.22
- **Node Version**: 14.4.0
- **Platform**: OSX
